
- name: Ensure fail2ban is installed
  community.general.zypper:
    name: fail2ban
    state: present

- name: Enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure fail2ban
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0600
  notify: Restart fail2ban

