---
- name: Update server
  community.general.zypper:
    name: '*'
    state: latest

- name: Install/remove packages
  include: packages.yml
  tags: packages

- name: Install/configure aide
  include: aide.yml
  tags: aide
