---
- name: Install/remove packages
  include: packages.yml
  tags: packages

- name: Configure firewall
  include: firewalld.yml
  tags: firewalld

- name: Configure chronyd
  include: chronyd.yml
  tags: chronyd

- name: Configure fail2ban
  include: fail2ban.yml
  tags: fail2ban

- name: General system hardening
  include: system.yml
  tags: system

- name: Remove system acc shells
  include: system_acc.yml
  tags: system_acc

- name: Coredump config
  include: coredump.yml
  tags: coredump

- name: Configure openssh-server
  include: sshd.yml
  tags: sshd

- name: Configure postfix
  include: postfix.yml
  tags: postfix

- name: Install/configure aide
  include: aide.yml
  tags: aide
