---
- name: Install packages
  community.general.zypper:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"

- name: Remove packages
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remove_packages }}"
