---
- name: Configure sshd
  block:

  - name: Replace MACs
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^MACs"
      line: "MACs hmac-sha2-512,hmac-sha2-256"

  - name: Replace Ciphers
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^Ciphers"
      line: "Ciphers aes128-ctr,aes192-ctr,aes256-ctr,\
        aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc"

  - name: Disable X Forwarding
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^X11Forwarding.*"
      line: "X11Forwarding no"

  notify: Restart sshd

- name: Set perms sshd_config
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
